//
//  subsets.h
//  entree
//
//  Created by MPB on 5/7/13.
//  Copyright (c) 2013 Quadrivio Corporation. All rights reserved.
//  License http://opensource.org/licenses/BSD-2-Clause
//          <YEAR> = 2013
//          <OWNER> = Quadrivio Corporation
//

//
// Create subsets of attribute columns to be used in individual decision trees in an ensemble
//

#ifndef entree_subsets_h
#define entree_subsets_h

#include "format.h"

#include <string>
#include <vector>

// ========== Function Headers =====================================================================

// make up to maxSubsets of columns, with column numbers in the range (0 to columnCount - 1),
// where each subset contains columnsPerSubset columns; subsets are generated by ordered
// deterministic permutations of clusters of column indexes
void makeSelectColSubsets(size_t columnCount,
                          size_t columnsPerSubset,
                          index_t maxSubsets,
                          std::vector< std::vector<size_t> >& subsets);

// make numSubsets subsets of columns, with column numbers in the range (0 to columnCount - 1),
// where each subset contains columnsPerSubset columns, randomly chosen
void makeRandomSelectColSubsets(size_t columnCount,
                                size_t columnsPerSubset,
                                index_t numSubsets,
                                std::vector< std::vector<size_t> >& subsets);


// component tests
void ctest_subsets(int& totalPassed, int& totalFailed, bool verbose);

// code coverage
void cover_subsets(bool verbose);

#endif
